apiVersion: v1
kind: Service
metadata:
  name: ahmed
  labels:
    name: ahmed-redis-service
    app: ahmed-app
spec:
  ports:
   - port: 6379
     targetPort: 6379
  selector:
    name: ahmed-redis
    app: ahmed-app
  