apiVersion: v1
kind: Service
metadata:
  name: ahmed-load-balancer
  labels:
    app: ahmed-app

spec:
  type: LoadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  selector:
     app: ahmed-app
     name: ahmed-python